# ***Question 1:***
Create a numpy array starting from 2 till 50 with a stepsize of 3. 



In [145]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# ***Questions 2:***
Accept two lists of 5 elements each from the user.  
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it. 

In [144]:
list_1 = []
list_2 = []

for i in range(5):
  lst_1 = int(input())
  list_1.append(lst_1)
print("list_1: ",list_1)

for j in range(5):
  lst_2 = int(input())
  list_2.append(lst_2)
print("list_2: ",list_2)

# Converting List to Array
arr_list1 = np.array(list_1)
arr_list2 = np.array(list_2)
print("Array Of list_1: ",arr_list1)
print("Array Of list_2: ",arr_list2)

# Concatenation of Arrays
arr_concat = np.concatenate((arr_list1,arr_list2))
print("Concatenation of 2 Arrays", arr_concat)

# Sorting of Array
arr_sort = np.sort(arr_concat)
print("Sorted Array: ",arr_sort)

15
36
1
25
85
list_1:  [15, 36, 1, 25, 85]
18
32
92
86
72
list_2:  [18, 32, 92, 86, 72]
Array Of list_1:  [15 36  1 25 85]
Array Of list_2:  [18 32 92 86 72]
Concatenation of 2 Arrays [15 36  1 25 85 18 32 92 86 72]
Sorted Array:  [ 1 15 18 25 32 36 72 85 86 92]


# ***Questions 3:***
Write a code snippet to find the dimensions of a N-Dimensional array(ndarray) and its size. 

In [142]:
# An array class in Numpy is called as ndarray

arr = np.arange(1,10)
print(arr)
print("No. of dimensions: ", arr.ndim) 
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print()

arr1 = np.arange(1,10).reshape(3,3) # array of 3*3 rows*columns
print(arr)
# or
# arr1 = np.array( [[ 1, 2, 3],
#                  [ 4, 5, 6],
#                  [ 7, 8, 9]] )

print("No. of dimensions(axis): ", arr1.ndim) 
print("Shape of array: ", arr1.shape)
print("Size of array: ", arr1.size)
print()

arr2 = np.arange(1,13).reshape(2,2,3) # array of 2*1(2*3 , 2*3)
print(arr2)
# or
# arr2 = np.array( [[[ 1, 2, 3],
#                  [ 4, 5, 6]],
#                  [[ 7, 8, 9],
#                  [ 10, 11, 12]]] ) 

print("No. of dimensions(axis): ", arr2.ndim) 
print("Shape of array: ", arr2.shape)
print("Size of array: ", arr2.size)

[1 2 3 4 5 6 7 8 9]
No. of dimensions:  1
Shape of array:  (9,)
Size of array:  9

[1 2 3 4 5 6 7 8 9]
No. of dimensions(axis):  2
Shape of array:  (3, 3)
Size of array:  9

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
No. of dimensions(axis):  3
Shape of array:  (2, 2, 3)
Size of array:  12


# ***Questions 4:***
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet   
Hint: np.newaxis, np.expand_dims

In [120]:
# Two different built-in functions to increase the dimension of an array are np.newaxis and np.expand_dims
# .newaxis is used to increase the dimension of the existing array by one more dimension

# numpy.newaxis object as a parameter at the index location in which you want to add the new axis
arr = np.arange(int(input()))
print("1D array (shape) :", arr.shape)
print(arr)
print()

two_d_array_row = arr[np.newaxis, :]
print("2D array for row is :", two_d_array_row.shape)
print(two_d_array_row)
print()

two_d_array_col = arr[:, np.newaxis]
print("2D array for column is :", two_d_array_col.shape)
print(two_d_array_col)

10
1D array (shape) : (10,)
[0 1 2 3 4 5 6 7 8 9]

2D array for row is : (1, 10)
[[0 1 2 3 4 5 6 7 8 9]]

2D array for column is : (10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


# ***Questions 5:*** 
Consider two square numpy arrays. Stack them vertically and horizontally.  
Hint: Use vstack(), hstack()

In [141]:
array_1 = np.square([1, 4, 5, 8, 9, 6, 3, 5, 7])  # square of numpy array
array_2 = np.square([4, 5, 8, 6, 9, 7, 4, 5, 6])  # square of numpy array

print("Horizontally Stacked :", np.hstack((array_1, array_2)))
print()

print("Vertically Stacked : ", np.vstack((array_1, array_2)))


Horizontally Stacked : [ 1 16 25 64 81 36  9 25 49 16 25 64 36 81 49 16 25 36]

Vertically Stacked :  [[ 1 16 25 64 81 36  9 25 49]
 [16 25 64 36 81 49 16 25 36]]


# ***Questions 6:*** 
How to get unique items and counts of unique items?

In [146]:
arr = np.array([4, 7, 6, 9, 5, 6, 5, 9, 3])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[3 1]
 [4 1]
 [5 2]
 [6 2]
 [7 1]
 [9 2]]
